version: "3"

services:
  passets-sensor:
    build:
      context: ./
    image: dsolab/passets-sensor:1.0.0
    container_name: passets-sensor
    environment:
      - interface=ens192
      - ip=ServerIP
      - port=ServerPort
      - tag=localhost
      - cache=1024
      - session=1024
      - timeout=3600
      - debug=off
      - http_filter_code=400,404,304
      - http_filter_type=audio/,video/,image/,font/,application/pdf,application/msword,application/javascript,text/javascript,text/css
    network_mode: host
    privileged: true
    restart: unless-stopped